name: dvc-novnc-jdk
services:
  dvc-novnc-jdk:
    image: hiro345g/dvc:novnc-jdk-202407
    container_name: dvc-novnc-jdk
    hostname: dvc-novnc-jdk
    init: true
    tty: true
    user: node
    working_dir: /home/node/workspace
    networks:
      dvc-net:
    volumes:
      - workspace-data:/home/node/workspace
      # - dot-sdkman:/usr/local/sdkman
      - vscode-server-extensions:/home/node/.vscode-server/extensions
      - type: bind
        source: ${SHARE_DIR:-../workspace_share}
        target: /share
    environment:
      ENV LANGUAGE: ja_JP.UTF-8
      ENV LANG: ja_JP.UTF-8
      ENV LC_ALL: ja_JP.UTF-8
      EDITOR: code
      NPM_CONFIG_USERCONFIG: ${NPM_CONFIG_USERCONFIG:-/home/node/.npmrc}

volumes:
  workspace-data:
    name: dvc-node-workspace-data
  vscode-server-extensions:
    name: dvc-vscode-server-extensions
  # dot-sdkman:
  #   name: dvc-node-dot-sdkman

networks:
  dvc-net:
    name: dvc-net